version: '3.7'

services:
  app:
    build: .
    command: yarn start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    env_file: .env
    networks:
      - backend
  
  db:
    image: postgres
    environment:
      POSTGRES_USER: equipments-crud
      POSTGRES_PASSWORD: equipments-crud-pass
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend:
    driver: bridge
