# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container: node:14

    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    # - name: Use Node.js
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: 14.x
    - name: Install dependencies
      run: npm ci
    - name: Lint code
      run: npm run lint
    - name: Run database migrations
      run: npx knex migrate:latest
      env:
        DATABASE_HOST: db
        DATABASE_PASSWORD: postgres
    - name: Run tests
      run: npm test
      env:
        DATABASE_HOST: db
        DATABASE_PASSWORD: postgres
    - uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: caiquecastro/equipments-crud:latest
