# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm ci
    - name: Lint code
      run: npm run lint
    - name: Create database
      run: touch database.sqlite3
    - name: Run database migrations
      run: npx knex migrate:latest
      env:
        DATABASE_URL: ./database.sqlite3
    - name: Run tests
      run: npm test
      env:
        DATABASE_URL: ./database.sqlite3
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      push: true
      tags: caiquecastro/equipments-crud:latest
